#!/usr/bin/env bash

hello() {
  local s=$1
  echo "hello $s!"
}

goodbye() {
  local s=$1
  echo "goodbye $s!"
}

# This is arithmatic expressions.
# equivalent to let command.
if (($# == 0)); then # $# is the number of arguments.
  # >&2 means redirect to stderr.
  echo 'name required!' >&2
  # Exit is a builtin command to terminate the script.
  exit 1
fi

# File descriptors for input/output redirection.
# 0 - stdin
# 1 - stdout
# 2 - stderr - stderr by default goes to the terminal.

for name in "$@"; do # $@ is all arguments as array.
  # String comparison in bash using wildcards. Outside of [[]], * means glob.
  if [[ $name == d* ]]; then
    hello "$name"
  elif [[ $name == b* ]]; then
    hello "$name"
  else
    goodbye "$name"
  fi
done
