#!/usr/bin/env bash

# Only reads one line by default.
read -r foo
echo "you said $foo"

# while read -r line; do
#   # This is the null command, it does nothing
#   :
# done

# Will read line by line.
#
# If I pipe in a file to this script. It will be printed line by line.
#
# ❯ cat file.txt | ./read-input
# you said foo
# we read line: bar
# we read line: baz
#
# or a better version would be
# ./read-input < file.txt
while read -r line || [[ -n $line ]]; do
  echo "we read line: $line"
done

# reading line by line is slow in bash, use cat, etc. whenever possible.
